fix(installer): do not attempt to use require without brunch
If the `--no-brunch` flag is set when creating a new project using
installer, e.g.

    mix phoenix.new /tmp/testapp --no-brunch

The line that is responsible for running the JavaScript for assets using
brunch is not included.

This prevents the JavaScript error:

 > ReferenceError: require is not defined

This closes issue #942